<a href="https://colab.research.google.com/github/HanHoHyeong/H3/blob/main/%EC%A0%95%EA%B7%9C%ED%99%94%EC%99%80_%EB%B6%84%ED%8F%AC%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

data = np.array([10, 12, 14, 15 ,18, 100, 13, 11, 12, 14, 13, 12, 15])


In [ ]:
mean = np.mean(data)
std = np.std(data)
z_score = (data - mean) / std
z_score

array([-0.42772485, -0.34151674, -0.25530863, -0.21220458, -0.08289241,
        3.45164008, -0.29841269, -0.3846208 , -0.34151674, -0.25530863,
       -0.29841269, -0.34151674, -0.21220458])

In [ ]:
max = np.max(data)
min = np.min(data)
normalized = (data - min) / (max - min)
normalized

array([0.        , 0.02222222, 0.04444444, 0.05555556, 0.08888889,
       1.        , 0.03333333, 0.01111111, 0.02222222, 0.04444444,
       0.03333333, 0.02222222, 0.05555556])

In [ ]:
data = np.array([10, 12, 14, 15, 18, 100, 13, 11, 12, 14, 13, 12, 15])
df = pd.DataFrame(data, columns=['df'])
q3_temp = df['df'].quantile(q=0.75)
q1_temp = df['df'].quantile(q=0.25)
iqr_temp = q3_temp - q1_temp
upper_temp = q3_temp + 1.5 * iqr_temp
lower_temp = q1_temp - 1.5 * iqr_temp

clean_data = data[(data >= lower_temp) & (data <= upper_temp)]
clean_data

array([10, 12, 14, 15, 18, 13, 11, 12, 14, 13, 12, 15])